//
//  IsoCountries.swift
//  Project2
//
//  Created by Jeffrey Carpenter on 6/25/20.
//  Copyright © 2020 Jeffrey Carpenter. All rights reserved.
//

import Foundation

struct IsoCountryInfo {
    
    let code: String
    let name: String
}

class IsoCountries {
    
    let allCountries: [IsoCountryInfo] = [
        IsoCountryInfo(code: "AD", name: "Andorra"),
        IsoCountryInfo(code: "AE", name: "United Arab Emirates"),
        IsoCountryInfo(code: "AF", name: "Afghanistan"),
        IsoCountryInfo(code: "AG", name: "Antigua and Barbuda"),
        IsoCountryInfo(code: "AI", name: "Anguilla"),
        IsoCountryInfo(code: "AL", name: "Albania"),
        IsoCountryInfo(code: "AM", name: "Armenia"),
        IsoCountryInfo(code: "AN", name: "Netherlands Antilles"),
        IsoCountryInfo(code: "AO", name: "Angola"),
        IsoCountryInfo(code: "AQ", name: "Antarctica"),
        IsoCountryInfo(code: "AR", name: "Argentina"),
        IsoCountryInfo(code: "AS", name: "American Samoa"),
        IsoCountryInfo(code: "AT", name: "Austria"),
        IsoCountryInfo(code: "AU", name: "Australia"),
        IsoCountryInfo(code: "AW", name: "Aruba"),
        IsoCountryInfo(code: "AX", name: "Åland Islands"),
        IsoCountryInfo(code: "AZ", name: "Azerbaijan"),
        IsoCountryInfo(code: "BA", name: "Bosnia and Herzegovina"),
        IsoCountryInfo(code: "BB", name: "Barbados"),
        IsoCountryInfo(code: "BD", name: "Bangladesh"),
        IsoCountryInfo(code: "BE", name: "Belgium"),
        IsoCountryInfo(code: "BF", name: "Burkina Faso"),
        IsoCountryInfo(code: "BG", name: "Bulgaria"),
        IsoCountryInfo(code: "BH", name: "Bahrain"),
        IsoCountryInfo(code: "BI", name: "Burundi"),
        IsoCountryInfo(code: "BJ", name: "Benin"),
        IsoCountryInfo(code: "BL", name: "Saint Barthélemy"),
        IsoCountryInfo(code: "BM", name: "Bermuda"),
        IsoCountryInfo(code: "BN", name: "Brunei Darussalam"),
        IsoCountryInfo(code: "BO", name: "Bolivia"),
        IsoCountryInfo(code: "BQ", name: "Caribbean Netherlands"),
        IsoCountryInfo(code: "BR", name: "Brazil"),
        IsoCountryInfo(code: "BS", name: "Bahamas"),
        IsoCountryInfo(code: "BT", name: "Bhutan"),
        IsoCountryInfo(code: "BV", name: "Bouvet Island"),
        IsoCountryInfo(code: "BW", name: "Botswana"),
        IsoCountryInfo(code: "BY", name: "Belarus"),
        IsoCountryInfo(code: "BZ", name: "Belize"),
        IsoCountryInfo(code: "CA", name: "Canada"),
        IsoCountryInfo(code: "CC", name: "Cocos (Keeling) Islands"),
        IsoCountryInfo(code: "CD", name: "Congo"),
        IsoCountryInfo(code: "CF", name: "Central African Republic"),
        IsoCountryInfo(code: "CG", name: "Congo"),
        IsoCountryInfo(code: "CH", name: "Switzerland"),
        IsoCountryInfo(code: "CI", name: "Côte d'Ivoire"),
        IsoCountryInfo(code: "CK", name: "Cook Islands"),
        IsoCountryInfo(code: "CL", name: "Chile"),
        IsoCountryInfo(code: "CM", name: "Cameroon"),
        IsoCountryInfo(code: "CN", name: "China"),
        IsoCountryInfo(code: "CO", name: "Colombia"),
        IsoCountryInfo(code: "CR", name: "Costa Rica"),
        IsoCountryInfo(code: "CU", name: "Cuba"),
        IsoCountryInfo(code: "CV", name: "Cape Verde"),
        IsoCountryInfo(code: "CW", name: "Curaçao"),
        IsoCountryInfo(code: "CX", name: "Christmas Island"),
        IsoCountryInfo(code: "CY", name: "Cyprus"),
        IsoCountryInfo(code: "CZ", name: "Czech Republic"),
        IsoCountryInfo(code: "DE", name: "Germany"),
        IsoCountryInfo(code: "DJ", name: "Djibouti"),
        IsoCountryInfo(code: "DK", name: "Denmark"),
        IsoCountryInfo(code: "DM", name: "Dominica"),
        IsoCountryInfo(code: "DO", name: "Dominican Republic"),
        IsoCountryInfo(code: "DZ", name: "Algeria"),
        IsoCountryInfo(code: "EC", name: "Ecuador"),
        IsoCountryInfo(code: "EE", name: "Estonia"),
        IsoCountryInfo(code: "EG", name: "Egypt"),
        IsoCountryInfo(code: "EH", name: "Western Sahara"),
        IsoCountryInfo(code: "ER", name: "Eritrea"),
        IsoCountryInfo(code: "ES", name: "Spain"),
        IsoCountryInfo(code: "ET", name: "Ethiopia"),
        IsoCountryInfo(code: "EU", name: "Europe"),
        IsoCountryInfo(code: "FI", name: "Finland"),
        IsoCountryInfo(code: "FJ", name: "Fiji"),
        IsoCountryInfo(code: "FK", name: "Falkland Islands (Malvinas)"),
        IsoCountryInfo(code: "FM", name: "Federated States of Micronesia"),
        IsoCountryInfo(code: "FO", name: "Faroe Islands"),
        IsoCountryInfo(code: "FR", name: "France"),
        IsoCountryInfo(code: "GA", name: "Gabon"),
        IsoCountryInfo(code: "GB-ENG", name: "England"),
        IsoCountryInfo(code: "GB-NIR", name: "Northern Ireland"),
        IsoCountryInfo(code: "GB-SCT", name: "Scotland"),
        IsoCountryInfo(code: "GB-WLS", name: "Wales"),
        IsoCountryInfo(code: "GB", name: "United Kingdom"),
        IsoCountryInfo(code: "GD", name: "Grenada"),
        IsoCountryInfo(code: "GE", name: "Georgia"),
        IsoCountryInfo(code: "GF", name: "French Guiana"),
        IsoCountryInfo(code: "GG", name: "Guernsey"),
        IsoCountryInfo(code: "GH", name: "Ghana"),
        IsoCountryInfo(code: "GI", name: "Gibraltar"),
        IsoCountryInfo(code: "GL", name: "Greenland"),
        IsoCountryInfo(code: "GM", name: "Gambia"),
        IsoCountryInfo(code: "GN", name: "Guinea"),
        IsoCountryInfo(code: "GP", name: "Guadeloupe"),
        IsoCountryInfo(code: "GQ", name: "Equatorial Guinea"),
        IsoCountryInfo(code: "GR", name: "Greece"),
        IsoCountryInfo(code: "GS", name: "South Georgia and the South Sandwich Islands"),
        IsoCountryInfo(code: "GT", name: "Guatemala"),
        IsoCountryInfo(code: "GU", name: "Guam"),
        IsoCountryInfo(code: "GW", name: "Guinea-Bissau"),
        IsoCountryInfo(code: "GY", name: "Guyana"),
        IsoCountryInfo(code: "HK", name: "Hong Kong"),
        IsoCountryInfo(code: "HM", name: "Heard Island and McDonald Islands"),
        IsoCountryInfo(code: "HN", name: "Honduras"),
        IsoCountryInfo(code: "HR", name: "Croatia"),
        IsoCountryInfo(code: "HT", name: "Haiti"),
        IsoCountryInfo(code: "HU", name: "Hungary"),
        IsoCountryInfo(code: "ID", name: "Indonesia"),
        IsoCountryInfo(code: "IE", name: "Ireland"),
        IsoCountryInfo(code: "IL", name: "Israel"),
        IsoCountryInfo(code: "IM", name: "Isle of Man"),
        IsoCountryInfo(code: "IN", name: "India"),
        IsoCountryInfo(code: "IO", name: "British Indian Ocean Territory"),
        IsoCountryInfo(code: "IQ", name: "Iraq"),
        IsoCountryInfo(code: "IR", name: "Islamic Republic of Iran"),
        IsoCountryInfo(code: "IS", name: "Iceland"),
        IsoCountryInfo(code: "IT", name: "Italy"),
        IsoCountryInfo(code: "JE", name: "Jersey"),
        IsoCountryInfo(code: "JM", name: "Jamaica"),
        IsoCountryInfo(code: "JO", name: "Jordan"),
        IsoCountryInfo(code: "JP", name: "Japan"),
        IsoCountryInfo(code: "KE", name: "Kenya"),
        IsoCountryInfo(code: "KG", name: "Kyrgyzstan"),
        IsoCountryInfo(code: "KH", name: "Cambodia"),
        IsoCountryInfo(code: "KI", name: "Kiribati"),
        IsoCountryInfo(code: "KM", name: "Comoros"),
        IsoCountryInfo(code: "KN", name: "Saint Kitts and Nevis"),
        IsoCountryInfo(code: "KP", name: "Democratic People's Republic of Korea"),
        IsoCountryInfo(code: "KR", name: "Republic of Korea"),
        IsoCountryInfo(code: "KW", name: "Kuwait"),
        IsoCountryInfo(code: "KY", name: "Cayman Islands"),
        IsoCountryInfo(code: "KZ", name: "Kazakhstan"),
        IsoCountryInfo(code: "LA", name: "Lao People's Democratic Republic"),
        IsoCountryInfo(code: "LB", name: "Lebanon"),
        IsoCountryInfo(code: "LC", name: "Saint Lucia"),
        IsoCountryInfo(code: "LI", name: "Liechtenstein"),
        IsoCountryInfo(code: "LK", name: "Sri Lanka"),
        IsoCountryInfo(code: "LR", name: "Liberia"),
        IsoCountryInfo(code: "LS", name: "Lesotho"),
        IsoCountryInfo(code: "LT", name: "Lithuania"),
        IsoCountryInfo(code: "LU", name: "Luxembourg"),
        IsoCountryInfo(code: "LV", name: "Latvia"),
        IsoCountryInfo(code: "LY", name: "Libya"),
        IsoCountryInfo(code: "MA", name: "Morocco"),
        IsoCountryInfo(code: "MC", name: "Monaco"),
        IsoCountryInfo(code: "MD", name: "Republic of Moldova"),
        IsoCountryInfo(code: "ME", name: "Montenegro"),
        IsoCountryInfo(code: "MF", name: "Saint Martin"),
        IsoCountryInfo(code: "MG", name: "Madagascar"),
        IsoCountryInfo(code: "MH", name: "Marshall Islands"),
        IsoCountryInfo(code: "MK", name: "Macedonia"),
        IsoCountryInfo(code: "ML", name: "Mali"),
        IsoCountryInfo(code: "MM", name: "Myanmar"),
        IsoCountryInfo(code: "MN", name: "Mongolia"),
        IsoCountryInfo(code: "MO", name: "Macao"),
        IsoCountryInfo(code: "MP", name: "Northern Mariana Islands"),
        IsoCountryInfo(code: "MQ", name: "Martinique"),
        IsoCountryInfo(code: "MR", name: "Mauritania"),
        IsoCountryInfo(code: "MS", name: "Montserrat"),
        IsoCountryInfo(code: "MT", name: "Malta"),
        IsoCountryInfo(code: "MU", name: "Mauritius"),
        IsoCountryInfo(code: "MV", name: "Maldives"),
        IsoCountryInfo(code: "MW", name: "Malawi"),
        IsoCountryInfo(code: "MX", name: "Mexico"),
        IsoCountryInfo(code: "MY", name: "Malaysia"),
        IsoCountryInfo(code: "MZ", name: "Mozambique"),
        IsoCountryInfo(code: "NA", name: "Namibia"),
        IsoCountryInfo(code: "NC", name: "New Caledonia"),
        IsoCountryInfo(code: "NE", name: "Niger"),
        IsoCountryInfo(code: "NF", name: "Norfolk Island"),
        IsoCountryInfo(code: "NG", name: "Nigeria"),
        IsoCountryInfo(code: "NI", name: "Nicaragua"),
        IsoCountryInfo(code: "NL", name: "Netherlands"),
        IsoCountryInfo(code: "NO", name: "Norway"),
        IsoCountryInfo(code: "NP", name: "Nepal"),
        IsoCountryInfo(code: "NR", name: "Nauru"),
        IsoCountryInfo(code: "NU", name: "Niue"),
        IsoCountryInfo(code: "NZ", name: "New Zealand"),
        IsoCountryInfo(code: "OM", name: "Oman"),
        IsoCountryInfo(code: "PA", name: "Panama"),
        IsoCountryInfo(code: "PE", name: "Peru"),
        IsoCountryInfo(code: "PF", name: "French Polynesia"),
        IsoCountryInfo(code: "PG", name: "Papua New Guinea"),
        IsoCountryInfo(code: "PH", name: "Philippines"),
        IsoCountryInfo(code: "PK", name: "Pakistan"),
        IsoCountryInfo(code: "PL", name: "Poland"),
        IsoCountryInfo(code: "PM", name: "Saint Pierre and Miquelon"),
        IsoCountryInfo(code: "PN", name: "Pitcairn"),
        IsoCountryInfo(code: "PR", name: "Puerto Rico"),
        IsoCountryInfo(code: "PS", name: "Palestine"),
        IsoCountryInfo(code: "PT", name: "Portugal"),
        IsoCountryInfo(code: "PW", name: "Palau"),
        IsoCountryInfo(code: "PY", name: "Paraguay"),
        IsoCountryInfo(code: "QA", name: "Qatar"),
        IsoCountryInfo(code: "RE", name: "Réunion"),
        IsoCountryInfo(code: "RO", name: "Romania"),
        IsoCountryInfo(code: "RS", name: "Serbia"),
        IsoCountryInfo(code: "RU", name: "Russian Federation"),
        IsoCountryInfo(code: "RW", name: "Rwanda"),
        IsoCountryInfo(code: "SA", name: "Saudi Arabia"),
        IsoCountryInfo(code: "SB", name: "Solomon Islands"),
        IsoCountryInfo(code: "SC", name: "Seychelles"),
        IsoCountryInfo(code: "SD", name: "Sudan"),
        IsoCountryInfo(code: "SE", name: "Sweden"),
        IsoCountryInfo(code: "SG", name: "Singapore"),
        IsoCountryInfo(code: "SH", name: "Ascension and Tristan da Cunha Saint Helena"),
        IsoCountryInfo(code: "SI", name: "Slovenia"),
        IsoCountryInfo(code: "SJ", name: "Svalbard and Jan Mayen Islands"),
        IsoCountryInfo(code: "SK", name: "Slovakia"),
        IsoCountryInfo(code: "SL", name: "Sierra Leone"),
        IsoCountryInfo(code: "SM", name: "San Marino"),
        IsoCountryInfo(code: "SN", name: "Senegal"),
        IsoCountryInfo(code: "SO", name: "Somalia"),
        IsoCountryInfo(code: "SR", name: "Suriname"),
        IsoCountryInfo(code: "SS", name: "South Sudan"),
        IsoCountryInfo(code: "ST", name: "Sao Tome and Principe"),
        IsoCountryInfo(code: "SV", name: "El Salvador"),
        IsoCountryInfo(code: "SX", name: "Sint Maarten (Dutch part)"),
        IsoCountryInfo(code: "SY", name: "Syrian Arab Republic"),
        IsoCountryInfo(code: "SZ", name: "Swaziland"),
        IsoCountryInfo(code: "TC", name: "Turks and Caicos Islands"),
        IsoCountryInfo(code: "TD", name: "Chad"),
        IsoCountryInfo(code: "TF", name: "French Southern Territories"),
        IsoCountryInfo(code: "TG", name: "Togo"),
        IsoCountryInfo(code: "TH", name: "Thailand"),
        IsoCountryInfo(code: "TJ", name: "Tajikistan"),
        IsoCountryInfo(code: "TK", name: "Tokelau"),
        IsoCountryInfo(code: "TL", name: "Timor-Leste"),
        IsoCountryInfo(code: "TM", name: "Turkmenistan"),
        IsoCountryInfo(code: "TN", name: "Tunisia"),
        IsoCountryInfo(code: "TO", name: "Tonga"),
        IsoCountryInfo(code: "TR", name: "Turkey"),
        IsoCountryInfo(code: "TT", name: "Trinidad and Tobago"),
        IsoCountryInfo(code: "TV", name: "Tuvalu"),
        IsoCountryInfo(code: "TW", name: "Taiwan"),
        IsoCountryInfo(code: "TZ", name: "United Republic of Tanzania"),
        IsoCountryInfo(code: "UA", name: "Ukraine"),
        IsoCountryInfo(code: "UG", name: "Uganda"),
        IsoCountryInfo(code: "UM", name: "US Minor Outlying Islands"),
        IsoCountryInfo(code: "US", name: "United States"),
        IsoCountryInfo(code: "UY", name: "Uruguay"),
        IsoCountryInfo(code: "UZ", name: "Uzbekistan"),
        IsoCountryInfo(code: "VA", name: "Holy See (Vatican City State)"),
        IsoCountryInfo(code: "VC", name: "Saint Vincent and the Grenadines"),
        IsoCountryInfo(code: "VE", name: "Bolivarian Republic of Venezuela"),
        IsoCountryInfo(code: "VG", name: "British Virgin Islands"),
        IsoCountryInfo(code: "VI", name: "U.S. Virgin Islands"),
        IsoCountryInfo(code: "VN", name: "Viet Nam"),
        IsoCountryInfo(code: "VU", name: "Vanuatu"),
        IsoCountryInfo(code: "WF", name: "Wallis and Futuna Islands"),
        IsoCountryInfo(code: "XK", name: "Kosovo"),
        IsoCountryInfo(code: "WS", name: "Samoa"),
        IsoCountryInfo(code: "YE", name: "Yemen"),
        IsoCountryInfo(code: "YT", name: "Mayotte"),
        IsoCountryInfo(code: "ZA", name: "South Africa"),
        IsoCountryInfo(code: "ZM", name: "Zambia"),
        IsoCountryInfo(code: "ZW", name: "Zimbabwe")
    ]
}
